// Same course list as the <select> in login.html/home.html, in data form
// so admin.html can build several selects (and one per student row) from
// a single source instead of duplicating markup.
const COURSES = [
  { label: "Building", options: [
    { value: "TCAD_E", label: "Technician Certificate in Architectural Drawing" },
    { value: "TCBE1", label: "Technician Certificate in Building and Civil Engineering Part 1" },
    { value: "TCBE2", label: "Technician Certificate in Building and Civil Engineering Part 2" },
    { value: "PL1", label: "Plumbing 1" },
    { value: "PL2", label: "Plumbing 2" },
    { value: "GC1", label: "General Construction 1" },
    { value: "GC2", label: "General Construction 2" },
    { value: "FM1", label: "Furniture Making 1" },
    { value: "FM2", label: "Furniture Making 2" },
  ]},
  { label: "Business Department", options: [
    { value: "ODC1", label: "Ordinary Diploma in Commerce 1" },
    { value: "ODC2", label: "Ordinary Diploma in Commerce 2" },
    { value: "GOA", label: "General Office Administration" },
    { value: "APP1", label: "Diploma in Administrative Principles and Practices 1" },
    { value: "APP2", label: "Diploma in Administrative Principles and Practices 2" },
  ]},
  { label: "Natural Sciences", options: [
    { value: "ODCS1", label: "Ordinary Diploma in Computer Science 1" },
    { value: "ODCS2", label: "Ordinary Diploma in Computer Science 2" },
    { value: "DO1", label: "Data Operations 1" },
    { value: "DO2", label: "Data Operations 2" },
    { value: "ODS1", label: "Ordinary Diploma in Science 1" },
    { value: "ODS2", label: "Ordinary Diploma in Science 2" },
  ]},
  { label: "Electrical", options: [
    { value: "ED1", label: "Technician Diploma in Electrical Department 1" },
    { value: "ED2", label: "Technician Diploma in Electrical Department 2" },
    { value: "EC1", label: "Technician Certificate in Electrical Engineering 1" },
    { value: "EC2", label: "Technician Certificate in Electrical Engineering 2" },
    { value: "EC3", label: "Technician Certificate in Electrical Engineering 3" },
    { value: "TC1", label: "Technician Certificate in Telecommunications 1" },
    { value: "TC2", label: "Technician Certificate in Telecommunications 2" },
    { value: "ETC1", label: "Elementary Certificate in Telecommunications 1" },
    { value: "ETC2", label: "Elementary Certificate in Telecommunications 2" },
    { value: "SAR", label: "Small Appliance Repairs 1" },
    { value: "SAR2", label: "Small Appliance Repairs 2" },
    { value: "AC1", label: "Refrigeration and Air Conditioning 1" },
    { value: "AC2", label: "Refrigeration and Air Conditioning 2" },
    { value: "ETE1", label: "Electrical Installation 1" },
    { value: "ETE2", label: "Electrical Installation 2" },
  ]},
  { label: "Mechanical", options: [
    { value: "TDM1", label: "Technician Diploma in Mechanical Engineering 1" },
    { value: "TDM2", label: "Technician Diploma in Mechanical Engineering 2" },
    { value: "TCE1", label: "Technician Certificate in Mechanical Engineering 1" },
    { value: "TCE2", label: "Technician Certificate in Mechanical Engineering 2" },
    { value: "MWE1", label: "Metal Work Engineering 1" },
    { value: "MWE2", label: "Metal Work Engineering 2" },
    { value: "MVR1", label: "Motor Vehicle Repairs 1" },
    { value: "MVR2", label: "Motor Vehicle Repairs 2" },
    { value: "MVES1", label: "Motor Vehicle Engine Systems 1" },
    { value: "MVES2", label: "Motor Vehicle Engine Systems 2" },
    { value: "W1", label: "Welding 1" },
    { value: "W2", label: "Welding 2" },
    { value: "CCAM1", label: "Craft Certificate in Agricultural Machinery 1" },
    { value: "CCAM2", label: "Craft Certificate in Agricultural Machinery 2" },
  ]},
  { label: "Land Surveying", options: [
    { value: "ODLS1", label: "Ordinary Diploma in Land Surveying 1" },
    { value: "ODLS2", label: "Ordinary Diploma in Land Surveying 2" },
  ]},
];